name:                 atproto-haskell-lexicon
version:              0.1.0.0
visibility:           public
id:                   atproto-haskell-lexicon-0.1.0.0-inplace
key:                  atproto-haskell-lexicon-0.1.0.0-inplace
license:              MIT
maintainer:           huw.campbell@gmail.com
author:               Huw Campbell
synopsis:             AT Protocol Lexicon schema types
description:
    Port of \@atproto\/lexicon – data types representing the AT Protocol
    Lexicon schema language used to describe records, queries, procedures,
    and subscriptions.

category:             Network
abi:                  inplace
exposed:              True
exposed-modules:
    ATProto.Lexicon ATProto.Lexicon.Json ATProto.Lexicon.Primitives
    ATProto.Lexicon.Types

import-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/build

library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/build

library-dirs-static:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/build

data-dir:
    /home/runner/work/atproto-haskell/atproto-haskell/atproto-lexicon/.

hs-libraries:         HSatproto-haskell-lexicon-0.1.0.0-inplace
depends:
    atproto-haskell-syntax-0.1.0.0-inplace base-4.22.0.0-fde1
    containers-0.7-9057eae47e89f02685a09966428ccdae490366a5a844b289b4f8308329a066ec
    text-2.1.4-af107aa316fbf04736723b1a784e57ed42184d22334a0827c65a8b2d0b1ee50b

haddock-interfaces:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/doc/html/atproto-haskell-lexicon/atproto-haskell-lexicon.haddock

haddock-html:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-lexicon-0.1.0.0/doc/html/atproto-haskell-lexicon
