name:                 atproto-haskell-xrpc
version:              0.1.0.0
visibility:           public
id:                   atproto-haskell-xrpc-0.1.0.0-inplace
key:                  atproto-haskell-xrpc-0.1.0.0-inplace
license:              MIT
maintainer:           huw.campbell@gmail.com
author:               Huw Campbell
synopsis:             AT Protocol XRPC client types and interface
description:
    Port of \@atproto\/xrpc – defines the 'XrpcClient' typeclass and the
    request\/response types for the AT Protocol XRPC transport layer.

category:             Network
abi:                  inplace
exposed:              True
exposed-modules:      ATProto.XRPC ATProto.XRPC.Client ATProto.XRPC.Types
import-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/build

library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/build

library-dirs-static:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/build

data-dir:
    /home/runner/work/atproto-haskell/atproto-haskell/atproto-xrpc/.

hs-libraries:         HSatproto-haskell-xrpc-0.1.0.0-inplace
depends:
    atproto-haskell-lexicon-0.1.0.0-inplace base-4.22.0.0-fde1
    bytestring-0.12.2.0-3f3f
    containers-0.7-9057eae47e89f02685a09966428ccdae490366a5a844b289b4f8308329a066ec
    text-2.1.4-af107aa316fbf04736723b1a784e57ed42184d22334a0827c65a8b2d0b1ee50b

haddock-interfaces:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/doc/html/atproto-haskell-xrpc/atproto-haskell-xrpc.haddock

haddock-html:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-xrpc-0.1.0.0/doc/html/atproto-haskell-xrpc
