name:                 atproto-haskell-syntax
version:              0.1.0.0
visibility:           public
id:                   atproto-haskell-syntax-0.1.0.0-inplace
key:                  atproto-haskell-syntax-0.1.0.0-inplace
license:              MIT
maintainer:           huw.campbell@gmail.com
author:               Huw Campbell
synopsis:
    AT Protocol identifier syntax: DIDs, handles, NSIDs, AT URIs, TIDs, record keys

description:
    Port of \@atproto\/syntax – validates and parses the core identifier types
    used in the AT Protocol: Decentralised Identifiers (DIDs), handles,
    Namespaced Identifiers (NSIDs), AT URIs, Timestamp IDs (TIDs), and
    record keys.

category:             Network
abi:                  inplace
exposed:              True
exposed-modules:
    ATProto.Syntax ATProto.Syntax.AtUri ATProto.Syntax.DID
    ATProto.Syntax.Handle ATProto.Syntax.NSID ATProto.Syntax.RecordKey
    ATProto.Syntax.TID

import-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/build

library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/build

library-dirs-static:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/build

data-dir:
    /home/runner/work/atproto-haskell/atproto-haskell/atproto-syntax/.

hs-libraries:         HSatproto-haskell-syntax-0.1.0.0-inplace
depends:              base-4.22.0.0-fde1 text-2.1.3-2a27
haddock-interfaces:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/doc/html/atproto-haskell-syntax/atproto-haskell-syntax.haddock

haddock-html:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-syntax-0.1.0.0/doc/html/atproto-haskell-syntax
