name:                 atproto-haskell-did
version:              0.1.0.0
visibility:           public
id:                   atproto-haskell-did-0.1.0.0-inplace
key:                  atproto-haskell-did-0.1.0.0-inplace
license:              MIT
maintainer:           huw.campbell@gmail.com
author:               Huw Campbell
synopsis:             AT Protocol DID document types
description:
    Port of \@atproto\/did – data types representing a resolved DID document.

category:             Network
abi:                  inplace
exposed:              True
exposed-modules:      ATProto.DID ATProto.DID.Document
import-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/build

library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/build

library-dirs-static:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/build

data-dir:
    /home/runner/work/atproto-haskell/atproto-haskell/atproto-did/.

hs-libraries:         HSatproto-haskell-did-0.1.0.0-inplace
depends:
    base-4.22.0.0-fde1
    text-2.1.4-af107aa316fbf04736723b1a784e57ed42184d22334a0827c65a8b2d0b1ee50b

haddock-interfaces:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/doc/html/atproto-haskell-did/atproto-haskell-did.haddock

haddock-html:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-did-0.1.0.0/doc/html/atproto-haskell-did
