name:                 atproto-haskell-crypto
version:              0.1.0.0
visibility:           public
id:                   atproto-haskell-crypto-0.1.0.0-inplace
key:                  atproto-haskell-crypto-0.1.0.0-inplace
license:              MIT
maintainer:           huw.campbell@gmail.com
author:               Huw Campbell
synopsis:             AT Protocol cryptographic key types and utilities
description:
    Port of \@atproto\/crypto – key type definitions and multikey encoding
    helpers for the P-256 and secp256k1 curves used in the AT Protocol.

category:             Network, Cryptography
abi:                  inplace
exposed:              True
exposed-modules:
    ATProto.Crypto ATProto.Crypto.Multikey ATProto.Crypto.Types

import-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/build

library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/build

library-dirs-static:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/build

data-dir:
    /home/runner/work/atproto-haskell/atproto-haskell/atproto-crypto/.

hs-libraries:         HSatproto-haskell-crypto-0.1.0.0-inplace
depends:              base-4.22.0.0-fde1 bytestring-0.12.2.0-3f3f
haddock-interfaces:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/doc/html/atproto-haskell-crypto/atproto-haskell-crypto.haddock

haddock-html:
    /home/runner/work/atproto-haskell/atproto-haskell/dist-newstyle/build/x86_64-linux/ghc-9.14.1/atproto-haskell-crypto-0.1.0.0/doc/html/atproto-haskell-crypto
